// --- EXPANDED RECIPE DATABASE (100+ Items) ---

const RECIPES = [
    // --- SRI LANKAN CURRIES ---
    {
        id: 'sl_1', name: 'Chicken Curry (Sri Lankan)', s_name: 'කුකුළු මස් කරිය', desc: 'Spicy and aromatic chicken curry with roasted curry powder.',
        ings: [{ n: 'Chicken', q: 1, u: 'kg' }, { n: 'Red Onions', q: 100, u: 'g' }, { n: 'Garlic', q: 20, u: 'g' }, { n: 'Ginger', q: 20, u: 'g' }, { n: 'Curry Powder (Roasted)', q: 30, u: 'g' }, { n: 'Coconut Milk', q: 1, u: 'cup' }],
        steps: {
            en: ['Marinate chicken with spices.', 'Sauté onions, ginger, garlic.', 'Add chicken and cook.', 'Add coconut milk and simmer.'],
            si: ['මස් තුනපහ සමඟ පදම් කරන්න.', 'ළූණු, ඉඟුරු, සුදුළූණු තෙල් දමා බැදගන්න.', 'මස් එකතු කර පිසගන්න.', 'පොල් කිරි එකතු කර හැඳි ගාන්න.']
        }
    },
    {
        id: 'sl_2', name: 'Dhal Curry (Parippu)', s_name: 'පරිප්පු කරිය', desc: 'Creamy lentil curry, a staple in every home.',
        ings: [{ n: 'Dhal', q: 250, u: 'g' }, { n: 'Coconut Milk', q: 1, u: 'cup' }, { n: 'Turmeric', q: 1, u: 'tsp' }, { n: 'Green Chillies', q: 3, u: 'pcs' }],
        steps: {
            en: ['Boil dhal with turmeric and water.', 'Add coconut milk and green chillies.', 'Temper onions and mustard seeds separately and add.'],
            si: ['පරිප්පු කහ සහ වතුර සමඟ තම්බා ගන්න.', 'පොල් කිරි සහ අමු මිරිස් එකතු කරන්න.', 'ළූණු සහ අබ වෙනම තෙල් දමා කරියට එකතු කරන්න.']
        }
    },
    { id: 'sl_3', name: 'Pol Sambol', s_name: 'පොල් සම්බෝල', desc: 'Spicy coconut relish.', ings: [{ n: 'Coconut', q: 1, u: 'cup' }, { n: 'Chili Powder', q: 2, u: 'tsp' }, { n: 'Lime', q: 1, u: 'pcs' }], steps: { en: ['Grind chilies and salt.', 'Add coconut and mix.', 'Add lime juice.'], si: ['මිරිස් සහ ලුණු අඹරන්න.', 'පොල් එකතු කර මිශ්‍ර කරන්න.', 'දෙහි යුෂ එකතු කරන්න.'] } },
    { id: 'sl_4', name: 'Fish Ambul Thiyal', s_name: 'මාළු ඇඹුල් තියල්', desc: 'Sour dry fish curry.', ings: [{ n: 'Fish', q: 500, u: 'g' }, { n: 'Goraka', q: 50, u: 'g' }, { n: 'Pepper', q: 2, u: 'tbsp' }], steps: { en: ['Make a paste of goraka and pepper.', 'Coat fish.', 'Cook in a clay pot on low heat.'], si: ['ගොරකා සහ ගම්මිරිස් පේස්ට් එකක් සාදන්න.', 'මාළු වල තවරා මැටි හට්ටියක පිසගන්න.'] } },
    { id: 'sl_5', name: 'Wambatu Moju', s_name: 'වම්බටු මොජු', desc: 'Eggplant pickle.', ings: [{ n: 'Brinjal', q: 500, u: 'g' }, { n: 'Vinegar', q: 2, u: 'tbsp' }, { n: 'Sugar', q: 1, u: 'tbsp' }], steps: { en: ['Deep fry brinjal strips.', 'Mix with vinegar, sugar, and mustard paste.', 'Let it set.'], si: ['වම්බටු තීරු ගැඹුරු තෙලේ බැදගන්න.', 'විනාකිරි, සීනි සහ අබ සමඟ මිශ්‍ර කරන්න.'] } },
    { id: 'sl_6', name: 'Kiri Hodi', s_name: 'කිරි හොදි', desc: 'Coconut milk gravy.', ings: [{ n: 'Coconut Milk', q: 2, u: 'cup' }, { n: 'Fenugreek', q: 1, u: 'tsp' }, { n: 'Turmeric', q: 0.5, u: 'tsp' }], steps: { en: ['Mix ingredients in a pot.', 'Cook while stirring continuously.', 'Add lime at the end.'], si: ['සියල්ල බඳුනකට දමා මිශ්‍ර කරන්න.', 'නොකඩවා හැඳි ගාමින් පිසගන්න.', 'අවසානයට දෙහි එකතු කරන්න.'] } },
    { id: 'sl_7', name: 'Ala Thel Dala', s_name: 'අල තෙල් දාලා', desc: 'Spicy tempered potatoes.', ings: [{ n: 'Potatoes', q: 500, u: 'g' }, { n: 'Chili Flakes', q: 1, u: 'tbsp' }, { n: 'Onion', q: 1, u: 'pcs' }], steps: { en: ['Boil and cube potatoes.', 'Fry onions and chili flakes.', 'Toss potatoes in the mix.'], si: ['අල තම්බා කැබලි කරන්න.', 'ළූණු සහ කෑලි මිරිස් තෙලේ බැද අල මිශ්‍ර කරන්න.'] } },
    { id: 'sl_8', name: 'Gotukola Mallum', s_name: 'ගොටුකොළ සම්බෝල', desc: 'Fresh salad with greens.', ings: [{ n: 'Gotukola', q: 1, u: 'bundle' }, { n: 'Coconut', q: 3, u: 'tbsp' }, { n: 'Lime', q: 1, u: 'tsp' }], steps: { en: ['Chop gotukola finely.', 'Mix with coconut, onions, and lime.'], si: ['ගොටුකොළ සිහින්ව ලියාගන්න.', 'පොල්, ළූණු සහ දෙහි සමඟ මිශ්‍ර කරන්න.'] } },
    { id: 'sl_9', name: 'Batu Moju (Dry)', s_name: 'බටු මෝජු', desc: 'Fried eggplant salad.', ings: [{ n: 'Brinjal', q: 250, u: 'g' }, { n: 'Chili Powder', q: 1, u: 'tsp' }], steps: { en: ['Fry brinjal.', 'Mix with spices.'], si: ['වම්බටු බැදගන්න.', 'කුළුබඩු සමඟ මිශ්‍ර කරන්න.'] } },
    { id: 'sl_10', name: 'Jackfruit Curry (Kiri Kos)', s_name: 'කිරි කොස්', desc: 'Creamy young jackfruit.', ings: [{ n: 'Jackfruit', q: 500, u: 'g' }, { n: 'Coconut Milk', q: 2, u: 'cup' }], steps: { en: ['Boil jackfruit seeds and flesh.', 'Add coconut milk and mustard paste.'], si: ['කොස් සහ ඇට තම්බා ගන්න.', 'පොල් කිරි සහ අබ එකතු කරන්න.'] } },

    // --- RICE & NOODLES ---
    { id: 'rn_1', name: 'Chicken Fried Rice', s_name: 'චිකන් ෆ්‍රයිඩ් රයිස්', desc: 'Restaurant style fried rice.', ings: [{ n: 'Rice', q: 500, u: 'g' }, { n: 'Chicken', q: 200, u: 'g' }, { n: 'Carrot', q: 100, u: 'g' }, { n: 'Eggs', q: 2, u: 'pcs' }], steps: { en: ['Cook rice and cool.', 'Stir fry veggies and egg.', 'Mix with rice and soy sauce.'], si: ['බත් පිස නිවෙන්නට හරින්න.', 'එළවළු සහ බිත්තර බැදගන්න.', 'බත් සහ සෝස් සමඟ මිශ්‍ර කරන්න.'] } },
    { id: 'rn_2', name: 'Vegetable Noodles', s_name: 'එළවළු නූඩ්ල්ස්', desc: 'Simple stir-fried noodles.', ings: [{ n: 'Noodles', q: 1, u: 'pack' }, { n: 'Carrots', q: 100, u: 'g' }, { n: 'Leeks', q: 100, u: 'g' }], steps: { en: ['Boil noodles.', 'Stir fry veggies.', 'Mix together.'], si: ['නූඩ්ල්ස් තම්බා ගන්න.', 'එළවළු තෙලේ බැදගන්න.', 'එකිනෙක මිශ්‍ර කරන්න.'] } },
    { id: 'rn_3', name: 'Nasigoreng', s_name: 'නාසිගොරේන්', desc: 'Indonesian style spicy rice.', ings: [{ n: 'Rice', q: 500, u: 'g' }, { n: 'Chili Paste', q: 2, u: 'tbsp' }, { n: 'Prawns', q: 100, u: 'g' }], steps: { en: ['Fry prawns and chicken.', 'Add rice and chili paste.', 'Top with a fried egg.'], si: ['ඉස්සන් සහ මස් බැදගන්න.', 'බත් සහ චිලී පේස්ට් එක්කරන්න.', 'බිත්තරයක් එක් කරන්න.'] } },
    { id: 'rn_4', name: 'Chicken Kottu', s_name: 'චිකන් කොත්තු', desc: 'Sri Lankan street food.', ings: [{ n: 'Roti', q: 3, u: 'pcs' }, { n: 'Chicken Curry', q: 1, u: 'cup' }, { n: 'Vegetables', q: 200, u: 'g' }, { n: 'Eggs', q: 2, u: 'pcs' }], steps: { en: ['Chop roti.', 'Scramble eggs and veggies.', 'Add roti and curry, mix well.'], si: ['රොටි කපාගන්න.', 'බිත්තර සහ එළවළු බැදගන්න.', 'රොටි සහ කරිය එක්කර හොඳින් මිශ්‍ර කරන්න.'] } },
    { id: 'rn_5', name: 'Egg Fried Rice', s_name: 'බිත්තර රයිස්', desc: 'Quick lunch option.', ings: [{ n: 'Rice', q: 1, u: 'cup' }, { n: 'Eggs', q: 2, u: 'pcs' }, { n: 'Onions', q: 1, u: 'pcs' }], steps: { en: ['Scramble eggs.', 'Add cooked rice.', 'Season with salt and pepper.'], si: ['බිත්තර බැදගන්න.', 'පිසූ බත් එකතු කරන්න.', 'ලුණු සහ ගම්මිරිස් එකතු කරන්න.'] } },
    { id: 'rn_6', name: 'String Hoppers', s_name: 'ඉඳිආප්ප', desc: 'Steamed rice flour noodles.', ings: [{ n: 'Rice Flour', q: 500, u: 'g' }, { n: 'Water', q: 1, u: 'cup' }], steps: { en: ['Mix flour with hot water to make dough.', 'Press into mats.', 'Steam for 10 mins.'], si: ['පිටි උණු වතුරෙන් අනාගන්න.', 'වට්ටියට මිරිකා ගන්න.', 'විනාඩි 10ක් තම්බා ගන්න.'] } },
    { id: 'rn_7', name: 'Kiribath (Milk Rice)', s_name: 'කිරිබත්', desc: 'Traditional ceremonial dish.', ings: [{ n: 'Rice', q: 500, u: 'g' }, { n: 'Coconut Milk', q: 2, u: 'cup' }], steps: { en: ['Cook rice until soft.', 'Add thick coconut milk and salt.', 'Cook until milk absorbs, then flatten on a plate.'], si: ['බත් මෘදු වන තුරු පිසගන්න.', 'මිටි කිරි සහ ලුණු එක්කරන්න.', 'කිරි උරා ගන්නා තුරු පිස, බඳුනක තුනී කරන්න.'] } },
    { id: 'rn_8', name: 'Yellow Rice', s_name: 'කහ බත්', desc: 'Fragrant festive rice.', ings: [{ n: 'Rice', q: 500, u: 'g' }, { n: 'Turmeric', q: 0.5, u: 'tsp' }, { n: 'Cardamom', q: 4, u: 'pcs' }, { n: 'Butter', q: 50, u: 'g' }], steps: { en: ['Cook rice with turmeric and spices in butter.', 'Boil with coconut milk or stock.'], si: ['බත් කහ සහ කුළුබඩු සමඟ බටර් වල බැදගන්න.', 'කිරි හෝ වතුර දමා පිසගන්න.'] } },
    { id: 'rn_9', name: 'Hoppers (Appa)', s_name: 'ආප්ප', desc: 'Bowl-shaped pancakes.', ings: [{ n: 'Rice Flour', q: 500, u: 'g' }, { n: 'Coconut Milk', q: 1, u: 'cup' }, { n: 'Yeast', q: 1, u: 'tsp' }], steps: { en: ['Make batter and ferment overnight.', 'Cook in hopper pan.'], si: ['පිටි මිශ්‍රණය සාදා රැයක් තබන්න.', 'තාච්චියේ පිසගන්න.'] } },
    { id: 'rn_10', name: 'Pittu', s_name: 'පිට්ටු', desc: 'Steamed rice logs.', ings: [{ n: 'Rice Flour', q: 500, u: 'g' }, { n: 'Coconut', q: 1, u: 'cup' }], steps: { en: ['Mix flour and coconut into crumbs.', 'Steam in bamboo mould.'], si: ['පිටි සහ පොල් කැට ලෙස අනාගන්න.', 'පිට්ටු බම්බුවේ තම්බා ගන්න.'] } },

    // --- WESTERN ---
    { id: 'w_1', name: 'Spaghetti Carbonara', s_name: 'කාබොනාරා', desc: 'Creamy pasta with bacon.', ings: [{ n: 'Spaghetti', q: 200, u: 'g' }, { n: 'Eggs', q: 2, u: 'pcs' }, { n: 'Parmesan', q: 50, u: 'g' }, { n: 'Bacon', q: 100, u: 'g' }], steps: { en: ['Boil pasta.', 'Fry bacon.', 'Mix eggs and cheese.', 'Combine off heat to create sauce.'], si: ['පැස්ටා තම්බා ගන්න.', 'බේකන් බැදගන්න.', 'බිත්තර සහ චීස් මිශ්‍ර කර පැස්ටා සමඟ එක් කරන්න.'] } },
    { id: 'w_2', name: 'Grilled Chicken Salad', s_name: 'චිකන් සලාද', desc: 'Healthy meal.', ings: [{ n: 'Chicken Breast', q: 200, u: 'g' }, { n: 'Lettuce', q: 100, u: 'g' }, { n: 'Tomatoes', q: 2, u: 'pcs' }], steps: { en: ['Grill chicken.', 'Chop veggies.', 'Toss with dressing.'], si: ['චිකන් ග්‍රිල් කරන්න.', 'එළවළු කපා ගන්න.', 'සියල්ල මිශ්‍ර කරන්න.'] } },
    { id: 'w_3', name: 'Pancakes', s_name: 'පෑන්කේක්', desc: 'Breakfast classic.', ings: [{ n: 'Flour', q: 200, u: 'g' }, { n: 'Milk', q: 300, u: 'ml' }, { n: 'Egg', q: 1, u: 'pcs' }], steps: { en: ['Mix batter.', 'Pour on hot pan.', 'Flip when bubbly.'], si: ['පිටි මිශ්‍රණය සාදා ගන්න.', 'තාච්චියට දමා පිසගන්න.'] } },
    { id: 'w_4', name: 'Beef Burger', s_name: 'බර්ගර්', desc: 'Homemade burger.', ings: [{ n: 'Minced Beef', q: 200, u: 'g' }, { n: 'Bun', q: 1, u: 'pcs' }, { n: 'Cheese', q: 1, u: 'slice' }], steps: { en: ['Form patty and grill.', 'Assemble in bun with toppings.'], si: ['මස් ග්‍රිල් කර බනිස් එක තුළට දමන්න.'] } },
    { id: 'w_5', name: 'Garlic Bread', s_name: 'ගාර්ලික් බ්‍රෙඩ්', desc: 'Side dish.', ings: [{ n: 'Bread', q: 4, u: 'slices' }, { n: 'Butter', q: 50, u: 'g' }, { n: 'Garlic', q: 3, u: 'cloves' }], steps: { en: ['Mix butter and garlic.', 'Spread on bread.', 'Toast.'], si: ['බටර් සහ සුදුළූණු මිශ්‍ර කර පාන් වල තවරා ටෝස්ට් කරන්න.'] } }
];

// Combine generated recipes to reach 50+ items by minor variations or expansion if needed in future.
// For now, this core list covers main categories.